server:
  error:
    include-stacktrace: always
    path: /error
    whitelabel:
      enabled: false
  port: 8000
  servlet:
    context-path: /morari
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: "0000"
    url: jdbc:sqlserver://localhost:1433;databaseName=campDB;TrustServerCertificate=True
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        '[allow_update_outside_transaction]': true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB
  thymeleaf:
    prefix: classpath:/templates/
  web:
    resources:
      cache:
        period: 0
      static-locations: classpath:/static/
